name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Install Playwright Browsers
        run: pnpm --filter @l1/site exec npx playwright install --with-deps
      - name: Start app
        run: pnpm --filter @l1/site start &
      - name: Wait for app
        run: npx wait-on http://localhost:3000
      - name: E2E tests (Playwright)
        run: pnpm --filter @l1/site test:e2e
      - name: Lighthouse CI
        run: pnpm --filter @l1/site lhci
