name: verify

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

concurrency:
  group: verify-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm verify
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: '1'
